const DEFAULT_LOGO='data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><rect width="100%" height="100%" rx="100" fill="%23fff4d6"/><text x="50%" y="54%" text-anchor="middle" font-size="70" fill="%23b36b00">ॐ</text></svg>';
let currentUser=null;let data=null;let cart=[];let lastInvoiceHTML='';
function users(){return JSON.parse(localStorage.getItem('sks_users')||'{}')}
function saveUsers(u){localStorage.setItem('sks_users',JSON.stringify(u))}
function createEmptyStore(username,storeName){return{username,profile:{name:storeName||'My General Store',bio:'Billing & Inventory App',phone:'',address:'',logo:DEFAULT_LOGO},products:[],purchases:[],sales:[]}}
function boot(){let u=users();if(!u.admin){u.admin={password:'1234',store:createEmptyStore('admin','Shree Khatu Shayam General Store')};saveUsers(u)}currentUser=localStorage.getItem('sks_current_user');if(currentUser&&users()[currentUser]){data=users()[currentUser].store;showApp()}else showAuthScreen()}
function showAuth(mode){document.getElementById('loginBox').classList.toggle('hidden',mode!=='login');document.getElementById('registerBox').classList.toggle('hidden',mode!=='register');document.getElementById('loginTab').classList.toggle('active',mode==='login');document.getElementById('registerTab').classList.toggle('active',mode==='register');document.getElementById('authMsg').innerText=''}
function showAuthScreen(){document.getElementById('authScreen').classList.remove('hidden');document.getElementById('app').classList.add('hidden')}
function registerUser(){let username=val('regUser').toLowerCase(),pass=val('regPass'),store=val('regStoreName');if(!username||!pass)return msg('Username aur password daalo');let u=users();if(u[username])return msg('Ye username already hai');u[username]={password:pass,store:createEmptyStore(username,store)};saveUsers(u);msg('Account ban gaya. Ab login karo.');showAuth('login')}
function login(){let username=val('loginUser').toLowerCase(),pass=val('loginPass');let u=users();if(!u[username]||u[username].password!==pass)return msg('Galat username/password');currentUser=username;data=u[username].store;localStorage.setItem('sks_current_user',username);showApp()}
function logout(){localStorage.removeItem('sks_current_user');currentUser=null;data=null;showAuthScreen()}
function msg(t){document.getElementById('authMsg').innerText=t}
function val(id){return document.getElementById(id).value.trim()}
function num(id){return Number(document.getElementById(id).value||0)}
function save(){let u=users();u[currentUser].store=data;saveUsers(u)}
function showApp(){document.getElementById('authScreen').classList.add('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('reportDate').valueAsDate=new Date();refreshAll();openPage('dashboard')}
function openPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');if(id==='reports')renderReports()}
function refreshAll(){renderProfile();renderProducts();fillProductSelects();renderPurchases();renderCart();renderDashboard();renderReports()}
function renderProfile(){let p=data.profile;['sideLogo','logoPreview'].forEach(id=>document.getElementById(id).src=p.logo||DEFAULT_LOGO);document.getElementById('sideStoreName').innerText=p.name;document.getElementById('sideUser').innerText='@'+currentUser;document.getElementById('topStoreName').innerText=p.name;document.getElementById('topBio').innerText=p.bio;document.getElementById('profileName').value=p.name;document.getElementById('profileBio').value=p.bio;document.getElementById('profilePhone').value=p.phone;document.getElementById('profileAddress').value=p.address;document.getElementById('previewName').innerText=p.name;document.getElementById('previewBio').innerText=p.bio;document.getElementById('previewPhone').innerText=p.phone}
function previewLogo(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{document.getElementById('logoPreview').src=r.result};r.readAsDataURL(f)}
function saveProfile(){let logo=document.getElementById('logoPreview').src;data.profile={name:val('profileName')||'My Store',bio:val('profileBio'),phone:val('profilePhone'),address:val('profileAddress'),logo};save();refreshAll();alert('Profile saved')}
function saveProduct(){let id=val('productEditId');let p={id:id||Date.now().toString(),name:val('pName'),category:val('pCategory'),purchase:num('pPurchase'),sale:num('pSale'),stock:num('pStock')};if(!p.name)return alert('Product name daalo');let i=data.products.findIndex(x=>x.id===p.id);if(i>=0)data.products[i]=p;else data.products.push(p);save();clearProductForm();refreshAll()}
function clearProductForm(){['productEditId','pName','pCategory','pPurchase','pSale','pStock'].forEach(id=>document.getElementById(id).value='')}
function editProduct(id){let p=data.products.find(x=>x.id===id);if(!p)return;document.getElementById('productEditId').value=p.id;document.getElementById('pName').value=p.name;document.getElementById('pCategory').value=p.category;document.getElementById('pPurchase').value=p.purchase;document.getElementById('pSale').value=p.sale;document.getElementById('pStock').value=p.stock;openPage('products')}
function deleteProduct(id){if(!confirm('Delete product?'))return;data.products=data.products.filter(p=>p.id!==id);save();refreshAll()}
function renderProducts(){document.getElementById('productTable').innerHTML=data.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.category)}</td><td>₹${p.purchase}</td><td>₹${p.sale}</td><td>${p.stock}</td><td><button onclick="editProduct('${p.id}')">Edit</button> <button class="danger" onclick="deleteProduct('${p.id}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="6">No products</td></tr>'}
function fillProductSelects(){let opts='<option value="">Select Product</option>'+data.products.map(p=>`<option value="${p.id}">${esc(p.name)} - Stock ${p.stock}</option>`).join('');document.getElementById('purProduct').innerHTML=opts;document.getElementById('saleProduct').innerHTML=opts}
function savePurchase(){let pid=val('purProduct'),p=data.products.find(x=>x.id===pid);if(!p)return alert('Product select karo');let q=num('purQty'),rate=num('purRate')||p.purchase;if(q<=0)return alert('Qty daalo');p.stock+=q;p.purchase=rate;data.purchases.push({id:Date.now().toString(),date:new Date().toISOString(),productId:pid,productName:p.name,supplier:val('purSupplier'),qty:q,rate,total:q*rate});save();['purSupplier','purQty','purRate'].forEach(id=>document.getElementById(id).value='');refreshAll()}
function renderPurchases(){document.getElementById('purchaseTable').innerHTML=data.purchases.slice().reverse().map(x=>`<tr><td>${date(x.date)}</td><td>${esc(x.productName)}</td><td>${esc(x.supplier)}</td><td>${x.qty}</td><td>₹${x.total}</td><td><button onclick="repeatPurchase('${x.id}')">Repeat</button></td></tr>`).join('')||'<tr><td colspan="6">No purchases</td></tr>'}
function repeatPurchase(id){let x=data.purchases.find(a=>a.id===id);if(!x)return;document.getElementById('purProduct').value=x.productId;document.getElementById('purSupplier').value=x.supplier;document.getElementById('purQty').value=x.qty;document.getElementById('purRate').value=x.rate;openPage('purchase')}
function addToCart(){let pid=val('saleProduct'),p=data.products.find(x=>x.id===pid),q=num('saleQty');if(!p)return alert('Product select karo');if(q<=0)return alert('Qty daalo');if(q>p.stock)return alert('Stock kam hai');cart.push({productId:p.id,name:p.name,qty:q,rate:p.sale,cost:p.purchase,total:q*p.sale,profit:q*(p.sale-p.purchase)});document.getElementById('saleQty').value='';renderCart()}
function removeCart(i){cart.splice(i,1);renderCart()}
function renderCart(){document.getElementById('cartTable').innerHTML=cart.map((c,i)=>`<tr><td>${esc(c.name)}</td><td>${c.qty}</td><td>₹${c.rate}</td><td>₹${c.total}</td><td><button class="danger" onclick="removeCart(${i})">X</button></td></tr>`).join('')||'<tr><td colspan="5">Cart empty</td></tr>';let t=cart.reduce((s,c)=>s+c.total,0);document.getElementById('cartTotal').innerText=t;renderInvoicePreview(false)}
function saveBill(){if(cart.length===0)return alert('Cart empty');let bill={id:Date.now().toString(),date:new Date().toISOString(),customer:val('custName')||'Customer',phone:val('custPhone'),items:[...cart],total:cart.reduce((s,c)=>s+c.total,0),profit:cart.reduce((s,c)=>s+c.profit,0)};cart.forEach(c=>{let p=data.products.find(x=>x.id===c.productId);if(p)p.stock-=c.qty});data.sales.push(bill);lastInvoiceHTML=invoiceHTML(bill,false);save();cart=[];document.getElementById('custName').value='';document.getElementById('custPhone').value='';refreshAll();document.getElementById('invoicePreview').innerHTML=lastInvoiceHTML;alert('Bill saved')}
function renderInvoicePreview(showProfit){let temp={id:'PREVIEW',date:new Date().toISOString(),customer:val('custName')||'Customer',phone:val('custPhone'),items:cart,total:cart.reduce((s,c)=>s+c.total,0),profit:cart.reduce((s,c)=>s+c.profit,0)};document.getElementById('invoicePreview').innerHTML=cart.length?invoiceHTML(temp,showProfit):'Cart me product add karte hi invoice yahan dikhega.'}
function invoiceHTML(b,showProfit){let p=data.profile;return `<div class="invoice"><div class="invoice-head"><img src="${p.logo||DEFAULT_LOGO}"><h2>${esc(p.name)}</h2><p>${esc(p.bio||'')}</p><p>${esc(p.phone||'')} ${esc(p.address||'')}</p></div><p><b>Bill:</b> ${b.id}<br><b>Date:</b> ${date(b.date)}<br><b>Customer:</b> ${esc(b.customer)} ${esc(b.phone||'')}</p><table><thead><tr><th>Item</th><th>Qty</th><th>Rate</th><th>Total</th></tr></thead><tbody>${b.items.map(i=>`<tr><td>${esc(i.name)}</td><td>${i.qty}</td><td>₹${i.rate}</td><td>₹${i.total}</td></tr>`).join('')}</tbody></table><h2>Total: ₹${b.total}</h2>${showProfit?`<p>Profit/Loss: ₹${b.profit}</p>`:''}<p style="text-align:center">Thank You</p></div>`}
function printInvoice(){let html=lastInvoiceHTML||document.getElementById('invoicePreview').innerHTML;if(!html||html.includes('Cart me'))return alert('Invoice preview empty hai');let old=document.body.innerHTML;document.body.innerHTML=`<div class="print-area">${html}</div>`;window.print();location.reload()}
function renderDashboard(){document.getElementById('dashProducts').innerText=data.products.length;document.getElementById('dashStock').innerText=data.products.reduce((s,p)=>s+p.stock,0);let today=ymd(new Date());let sales=data.sales.filter(s=>ymd(new Date(s.date))===today);document.getElementById('dashSales').innerText='₹'+sales.reduce((a,b)=>a+b.total,0);document.getElementById('dashProfit').innerText='₹'+sales.reduce((a,b)=>a+b.profit,0);document.getElementById('lowStockList').innerHTML=data.products.filter(p=>p.stock<=5).map(p=>`<p>${esc(p.name)} - ${p.stock}</p>`).join('')||'<p>No low stock</p>'}
function renderReports(){let d=val('reportDate')||ymd(new Date());let sales=data.sales.filter(s=>ymd(new Date(s.date))===d),purs=data.purchases.filter(p=>ymd(new Date(p.date))===d);let st=sales.reduce((a,b)=>a+b.total,0),pf=sales.reduce((a,b)=>a+b.profit,0),pt=purs.reduce((a,b)=>a+b.total,0);document.getElementById('reportBox').innerHTML=`<div class="report-content"><h2>${esc(data.profile.name)} - Daily Report</h2><p>Date: ${d}</p><h3>Sales: ₹${st}</h3><h3>Purchase: ₹${pt}</h3><h3>Profit/Loss: ₹${pf}</h3><h3>Bills</h3>${sales.map(s=>`<p>${date(s.date)} - ${esc(s.customer)} - ₹${s.total}</p>`).join('')||'No sales'}<h3>Purchases</h3>${purs.map(p=>`<p>${date(p.date)} - ${esc(p.productName)} - ₹${p.total}</p>`).join('')||'No purchases'}</div>`}
function printReport(){let html=document.getElementById('reportBox').innerHTML;if(!html)return;let old=document.body.innerHTML;document.body.innerHTML=`<div class="print-area">${html}</div>`;window.print();location.reload()}
function downloadBackup(){let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${currentUser}-store-backup.json`;a.click()}
function restoreBackup(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);save();refreshAll();alert('Backup restored')}catch(err){alert('Invalid backup file')}};r.readAsText(f)}
function resetStore(){if(!confirm('Current store ka data delete hoga?'))return;data=createEmptyStore(currentUser,data.profile.name);save();refreshAll()}
function date(d){return new Date(d).toLocaleString('en-IN')}function ymd(d){return d.toISOString().slice(0,10)}function esc(s){return String(s||'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
window.addEventListener('input',e=>{if(['custName','custPhone'].includes(e.target.id))renderInvoicePreview(false)});if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}document.addEventListener('DOMContentLoaded',boot);
